parameters:
#    blogger_blog.example.class: Blogger\BlogBundle\Example

services:
#    blogger_blog.example:
#        class: %blogger_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    blogger.twig.blogbundle_extension_truncate:
        class: Blogger\BlogBundle\Twig\Extensions\TwigTruncate
        tags:
            - { name: twig.extension }

    blogger.twig.blogbundle_extension_createdago:
        class: Blogger\BlogBundle\Twig\Extensions\CreatedAgo
        tags:
            - { name: twig.extension }

    blogger.twig.blogbundle_extension_gravatar:
            class: Blogger\BlogBundle\Twig\Extensions\Gravatar
            tags:
                - { name: twig.extension }