parameters:
#    blogger_user.example.class: Blogger\UserBundle\Example

services:
#    blogger_user.example:
#        class: %blogger_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
